---

#apiVersion: apps/v1
apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: c1
  labels:
    comp: c1

spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      comp: c1
  template:
    metadata:
      labels:
        comp: c1
    spec:
      containers:
      - name: main
        image: opsani/co-http:latest
        args: [ 'busy=400' ]
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service

metadata:
  name: c1

spec:
  selector:
    comp: c1
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
